red:
  build: .
  volumes:
    - /opt/devel/workspaces/uji/red/data:/data
    - /var/run/docker.sock:/var/run/docker.sock
    - /opt/devel/workspaces/uji/red/src:/src
  ports:
    - "5000:5000"

nginx:
  image: nginx
  volumes:
    - /opt/devel/workspaces/uji/red/data/nginx.conf.d:/etc/nginx/conf.d

  ports:
    - "8080:80"
    - "8443:443"
