red:
  build: .
  volumes:
    - /opt/devel/workspaces/uji/red/data:/data
    - /var/run/docker.sock:/var/run/docker.sock
    - /opt/devel/workspaces/uji/red/src:/src
  ports:
    - "5000:5000"

nginx:
  image: nginx
  volumes:
    - /opt/devel/workspaces/uji/red/data/nginx.conf.d:/etc/nginx/conf.d
    - /opt/devel/workspaces/uji/red/data:/data
  environment:
   - NGINX_HOST=localhost
   - NGINX_PORT=80
   - NGINX_DOCUMENT_ROOT=/data/nginx.document_root
  ports:
    - "8080:80"
    - "8443:443"
  command: /bin/bash -c "envsubst < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
